### ISSUE TITLE
normalize_codex2_ns_noK throws an error

### ISSUE THREAD

**Issue by shashwatsahay** [rujinwang/SCOPE#14]
Hi,

When I run my sample with 10x data the function `normalise_codex2_ns_noK` gives this error

```
Adopt arithmetic mean instead of geometric mean

Computing normalization with no latent factors

Error in smooth.spline(gc_qc, z): missing or infinite values in inputs are not allowed
Traceback:

1. normalize_codex2_ns_noK(Y_qc = Y, gc_qc = ref$gc, norm_index = which(Gini <= 
 .     0.12))
2. apply(gcfit, 2, function(z) {
 .     spl <- smooth.spline(gc_qc, z)
 .     temp <- predict(spl, gc_qc)$y
 .     temp[temp <= 0] <- min(temp[temp > 0])
 .     temp
 . })
3. FUN(newX[, i], ...)
4. smooth.spline(gc_qc, z)
5. stop("missing or infinite values in inputs are not allowed")
```

**Comment by yuchaojiang** [comment]
Most likely your GC content has some missing values.
Yuchao

On Mar 23, 2023, at 8:01 AM, Shashwat Sahay ***@***.******@***.***>> wrote:



Hi,

When I run my sample with 10x data the function normalise_codex2_ns_noK gives this error

Adopt arithmetic mean instead of geometric mean

Computing normalization with no latent factors

Error in smooth.spline(gc_qc, z): missing or infinite values in inputs are not allowed
Traceback:

1. normalize_codex2_ns_noK(Y_qc = Y, gc_qc = ref$gc, norm_index = which(Gini <=
 .     0.12))
2. apply(gcfit, 2, function(z) {
 .     spl <- smooth.spline(gc_qc, z)
 .     temp <- predict(spl, gc_qc)$y
 .     temp[temp <= 0] <- min(temp[temp > 0])
 .     temp
 . })
3. FUN(newX[, i], ...)
4. smooth.spline(gc_qc, z)
5. stop("missing or infinite values in inputs are not allowed")

**Comment by shashwatsahay** [comment]
Hi 

I had a proper look at this and the problem is not in the GC values 

I am attaching an Rdata file which contains the Y and ref according to the SCOPE tutorial so that you can replicate the error
[data.zip](https://github.com/rujinwang/SCOPE/files/12185013/data.zip)

```
   load(data.RData)
   Y_qc <- Y
    gc_qc <- ref$gc

    Y.nonzero <- Y_qc[apply(Y_qc, 1, function(x) {
        !any(x == 0)
        }), , drop = FALSE]
    if(dim(Y.nonzero)[1] <= 10){
        message("Adopt arithmetic mean instead of geometric mean")
        pseudo.sample <- apply(Y_qc, 1, mean)
        Ntotal <- apply(apply(Y_qc, 2, function(x) {
            x/pseudo.sample
        }), 2, median, na.rm = TRUE)
    } else{
        pseudo.sample <- apply(Y.nonzero, 1, function(x) {
            exp(sum(log(x))/length(x))
            })
        Ntotal <- apply(apply(Y.nonzero, 2, function(x) {
            x/pseudo.sample
        }), 2, median)
    }
    N <- round(Ntotal/median(Ntotal) * median(colSums(Y_qc)))
    Nmat <- matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc), data = N,
        byrow = TRUE)

    message("Computing normalization with no latent factors")
    maxiter <- 10
    maxhiter <- 50
    BHTHRESH <- 1e-04
    HHTHRESH <- 1e-05
    iter <- 1
    fhat <- matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc), data = 0)
    fhatnew <- matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc))
    betahat <- rep(1, nrow(Y_qc))
    betahatmat <- matrix(nrow = nrow(Y_qc), ncol = ncol(Y_qc),
        data = betahat, byrow = FALSE)
    bhdiff <- rep(Inf, maxiter)
    fhdiff <- rep(Inf, maxiter)
    betahatlist <- list(length = maxiter)
    fhatlist <- list(length = maxiter)
```
at this point once we enter the loop and do `gcfit <- Y_qc/Nmat/betahatmat` then looking into ` gcfit[, 'Cell_1017'] ` provides us with inf and Nan values

On further investigation the likely cause of this is median for the cell being 0 due to sparsity maybe we can somehow have this in the quality control or instead of median use a different metric here

`length(which(Y_qc[, 'Cell_1017']==0))` =  2137
`length(Y_qc[, 'Cell_1017'])` = 4228
