### ISSUE TITLE
Running SCOPE on a matrix of cells by bins

### ISSUE THREAD

**Issue by pedrofale** [rujinwang/SCOPE#7]
Hi all,
Thanks for this nice tool! I would like to run SCOPE on simulated data consisting of a simple cells by bins matrix of read counts. When I try to do this following the steps in the vignette, I use the `normalize_codex2_ns_noK` function with `Y_qc` set to the simulated matrix, and `gc` simply a vector of ones for all the bins. This gives an error though:
```
Error in smooth.spline(gc_qc, z) : 
  'tol' must be strictly positive and finite
```
which I think is due to the fact that my `gc` is a constant vector. How can I get around this issue?

**Comment by rujinwang** [comment]
Hi @pedrofale , 
Thanks for your interest in SCOPE. 
smooth.spline() does not work for a constant vector since its degree of freedom is determined by the number of unique gc values (check the documentation of smooth.spline function). Must be in (1,nx], nx the number of unique x values. In your extreme case, it fails to determine degree of freedom and number of knots.  
Also, I don't think a constant vector of gc content makes any sense. For your simulated data, I guess you could try a uniformly distributed gc values. 

Best, 
Rujin
